### ISSUE TITLE
No module named 'Adafruit_GPIO.I2C'

### ISSUE THREAD

**Issue by LALAJAZMIN** [agrc/AmdButler#45]
Hi i have a problem 
import Adafruit_CharLCD
when importing this address gives me this error

ModuleNotFoundError: No module named 'Adafruit_GPIO.I2C'

**Comment by stdavis** [comment]
I think that you have the wrong repository. This repo hosts a tool (which is no longer maintained) for managing JavaScript module import statements (in AMD format).

Your issue seems to be related to a bad python import. Perhaps [this article](http://www.daveoncode.com/2017/03/07/how-to-solve-python-modulenotfound-no-module-named-import-error/) would help.
